AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 10
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01
# MLFLOW_TRACKING_URI=https://dagshub.com/bhaveshk22/Kidney_disease_classification.mlflow
# MLFLOW_TRACKING_USERNAME=bhaveshk22
# MLFLOW_TRACKING_PASSWORD=9b876976720ed89fe803c5e807f3867b32a5967e